
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TechBlogWebsite.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Category
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {

        this.Categories1 = new HashSet<Category>();

        this.Forums = new HashSet<Forum>();

        this.Posts = new HashSet<Post>();

    }


    public int CategoryID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Nullable<int> ParentID { get; set; }

    public string Link { get; set; }

    public string Meta { get; set; }

    public Nullable<bool> Hide { get; set; }

    public Nullable<int> Order { get; set; }

    public Nullable<System.DateTime> DateBegin { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Category> Categories1 { get; set; }

    public virtual Category Category1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Forum> Forums { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Post> Posts { get; set; }

}

}
