//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBlogWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string company_name { get; set; }
        public string full_name { get; set; }
        public string current_position { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string how_heard { get; set; }
        public string job_description { get; set; }
        public Nullable<bool> is_posted { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string link { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
    
        public virtual User User { get; set; }
    }
}
